apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: supermario-container
        image: jegankumard/supermario:latest 
        ports:
        - containerPort: 80
